name = "99copias-app"
compatibility_date = "2026-08-09"

[[kv_namespaces]]
binding = "KV"
id = "c49dd492057148859db7e2e7acd6a61b"

[[d1_databases]]
binding = "DB"
database_name = "99copias_db"
database_id = "fd561572-08f1-4411-8c5e-88a479e6b25b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "99copiasbucket"